### ISSUE TITLE
NetBox and IPF Config

### ISSUE THREAD

**Issue by Mark32** [jeremyschulman/ipf-netbox#18]
Hi, where/how do you define the ip, credentials etc for each platform?

For NetBox I see a setup.env in devtest-env but not sure how that is used once configured. There is also a const.py but also doesn't have the IPF defined. So actually not sure what to actually configure and where.

Please can I get some quick and dirty instructions for configuring/using please?

Thanks
Mark

**Comment by jeremyschulman** [comment]
@Mark32 - my apologies for the delay responding.  This tool requires a TOML based configuration file; the same as in the [netcfgbu](https://github.com/jeremyschulman/netcfgbu) project.  The additional section for ipf-netcfgbu is:

````toml
[ipfabric]
    server_url = "$IPF_ADDR"
    credentials.username = "$IPF_USERNAME"
    credentials.password = "$IPF_PASSWORD"
````

The environment variables can be of your choosing; I just happen to name them as above.

Hope this helps!
